export const ENGAGEMENT_TOKEN_RADIUS = 12;
export const ENGAGEMENT_PREFERRED_CLEARANCE = 10;
export const ENGAGEMENT_MINIMUM_CLEARANCE = 4;
export const ENGAGEMENT_CHAIN_VISIBLE_CLEARANCE = 10;
/** Actor branches win only when shorter than this fraction of a valid spoke. */
export const ENGAGEMENT_BRANCH_TO_DIRECT_LENGTH_RATIO = 0.7;
export const ENGAGEMENT_SPACIOUS_CLEARANCES = [
  22,
  16,
  ENGAGEMENT_PREFERRED_CLEARANCE,
  ENGAGEMENT_MINIMUM_CLEARANCE
] as const;
